### ISSUE TITLE
BUG - Plugin crashes with SEGV after upgrade to 3.x

### ISSUE THREAD

**Issue by grubbins** [standup-raven/standup-raven#216]
**Summary**
On versions 3.1.1 and also latest code, the plugin reliably crashes with a nil pointer dereference not long after starting.

**Steps To Reproduce**
0. Mattermost version 5.27.1 with many standups configured for channels
1. Upgrade standup raven from 2.5.2 to 3.1.1 or current head
2. Disable and re-enable plugin
3. Wait for it...
4. Read stacktrace of SEGV in logs
5. Repeat from step 2 

**Expected behavior**
No SEGV

**Observed Behavior**
```
2020-11-16T08:46:13.734+1100    debug   mlog/sugar.go:15        Fetching standup config for channel: f5hbhq6sw3ncpfhgai79zgy3yy {"plugin_id": "standup-raven", "Fetching standup config for channel: f5hbhq6sw3ncpfhgai79zgy3yy": "[]"}
e": "200"}
2020-11-16T08:46:14.536+1100    debug   mlog/sugar.go:15        Fetching notification status for channel: f5hbhq6sw3ncpfhgai79zgy3yy    {"plugin_id": "standup-raven", "Fetching notification status for channel: f5hbhq6sw3ncpfhgai79zgy3yy": "[]"}
2020-11-16T08:46:14.536+1100    debug   mlog/sugar.go:15        Fetching standup config for channel: f5hbhq6sw3ncpfhgai79zgy3yy {"plugin_id": "standup-raven", "Fetching standup config for channel: f5hbhq6sw3ncpfhgai79zgy3yy": "[]"}
2020-11-16T08:46:14.551+1100    debug   mlog/sugar.go:15        Channel [f5hbhq6sw3ncpfhgai79zgy3yy] needs standup report       {"plugin_id": "standup-raven", "Channel [f5hbhq6sw3ncpfhgai79zgy3yy] needs standup report": "[]"}
2020-11-16T08:46:14.551+1100    debug   mlog/sugar.go:15        Processing channel: tass9ycqbfrrdp4ms34z834wac  {"plugin_id": "standup-raven", "Processing channel: tass9ycqbfrrdp4ms34z834wac": "[]"}
2020-11-16T08:46:14.551+1100    debug   mlog/sugar.go:15        Fetching standup config for channel: tass9ycqbfrrdp4ms34z834wac {"plugin_id": "standup-raven", "Fetching standup config for channel: tass9ycqbfrrdp4ms34z834wac": "[]"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      panic: runtime error: invalid memory address or nil pointer dereference {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf03b04]  {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      goroutine 12 [running]: {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      github.com/teambition/rrule-go.(*RRule).Iterator(0x0, 0x0)      {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/pkg/mod/github.com/standup-raven/rrule-go@v1.5.1-0.20200606021409-a2ced8306e77/rrule.go:807 +0x94      {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      github.com/teambition/rrule-go.(*RRule).Between(0x0, 0x0, 0xed7425834, 0xc000948060, 0x0, 0xed743a9f0, 0xc000948060, 0xc000948000, 0x0, 0x0, ...)       {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/pkg/mod/github.com/standup-raven/rrule-go@v1.5.1-0.20200606021409-a2ced8306e77/rrule.go:838 +0x49      {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      github.com/standup-raven/standup-raven/server/standup/notification.isStandupDay(0xc0001e2000, 0x0)      {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/src/github.com/standup-raven/standup-raven/server/standup/notification/notification.go:694 +0x2ea      {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      github.com/standup-raven/standup-raven/server/standup/notification.filterChannelNotification(0xc000393440, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)    {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/src/github.com/standup-raven/standup-raven/server/standup/notification/notification.go:285 +0x593      {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      github.com/standup-raven/standup-raven/server/standup/notification.SendNotificationsAndReports(0x0, 0x0)        {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/src/github.com/standup-raven/standup-raven/server/standup/notification/notification.go:45 +0x13e       {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      main.(*Plugin).runner.func1(0xc0003d2580)       {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/src/github.com/standup-raven/standup-raven/server/plugin.go:217 +0x5f  {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53      created by main.(*Plugin).runner        {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.557+1100    debug   plugin/hclog_adapter.go:53              /Users/harshilsharma/codebase/go/src/github.com/standup-raven/standup-raven/server/plugin.go:215 +0x3f  {"plugin_id": "standup-raven"}
2020-11-16T08:46:14.560+1100    debug   plugin/hclog_adapter.go:51      plugin process exited   {"plugin_id": "standup-raven", "wrapped_extras": "path/data/mattermost/server/server-plugins/standup-raven/server/plugin.exepid93455errorexit status 2"}
```
After rolling back to 2.5.2 we were able to continue.

**Environment**
-  Mattermost version: 5.27.1
-  OS: CentOS 7

**Comment by grubbins** [comment]
The panic always seemed to occur at the same point - fetching standup config for channel with id `tass9ycqbfrrdp4ms34z834wac`. I don't know how to inspect the standup config of that channel to see what's wrong, but I think this means I can at least reproduce the problem.

**Comment by harshilsharma63** [comment]
@grubbins it looks like the data migration didn't go through well for. Can you see the logs for the time when you updated from 2.5 to 3.1?

**Comment by grubbins** [comment]
I'm looking, but not finding anything that looks relevant. Would it have required debug-level logs? We did not have debug logs enabled at the time of the upgrade.

**Comment by grubbins** [comment]
Looking further back, I see occasional instances (before we upgraded) of:
```
dpanic  zap@v1.15.0/sugar.go:191        Ignored key without a value.    {"plugin_id": "standup-raven", "ignored": "Error occurred processing /standup"}
```
and sometimes randomly this:
```
info    go-plugin@v1.3.0/stream.go:15   {"channelId":"qy3utsi51jb5zcr66suf8z89bh", ... lots of fields ... }
```

**Comment by grubbins** [comment]
With a local build of the plugin I was able to print the JSON of the standup `Config` for one of the breaking channels:
```json
{
  "channelId": "tjwshcz8gfyupk8h93t8yyuhir",
  "windowOpenTime": "15:00",
  "windowCloseTime": "15:15",
  "reportFormat": "user_aggregated",
  "members": [
    "em7tudx9jfbjuq35n61wnp63se",
    "meywagac5pfg8j6dnj1e8a8oyr",
    "tq4hq789n3bk5yahs3qor6epdw",
    "zgdhkbjn8tydz87ckz3muieqyr"
  ],
  "sections": [
    "What is the status of your tasks?"
  ],
  "enabled": true,
  "timezone": "America/Chicago",
  "windowOpenReminderEnabled": true,
  "windowCloseReminderEnabled": true,
  "scheduleEnabled": true
}
```

Indeed the fields `rrule`, `rruleString` and `startDate` are absent but are assumed later to be present. Just looking into whether I can make a quick fix.

**Comment by grubbins** [comment]
I think I will try forcing the database version back to 2.0.0 and letting it try the upgrade again.

**Comment by grubbins** [comment]
That seems to have worked. I wonder if the issue here is that the plugin was downgraded at some point.

**Comment by iprok** [comment]
Hello! We have just faced the issue. Can you tell us the steps to repair database?

**Comment by iprok** [comment]
@grubbins can you help with this please?
