### ISSUE TITLE
BUG - Plugin Not Working

### ISSUE THREAD

**Issue by wgbeckmann** [standup-raven/standup-raven#93]
Hi, the Raven Symbol is shown, but the /standup command is not working.

These are the logs (filtered with the word plugin):
```
{"level":"info","ts":1563781389.946745,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
{"level":"debug","ts":1563781391.4587915,"caller":"go-plugin/client.go:504","msg":"starting plugin","plugin_id":"standup-raven","wrapped_extras":"pathplugins/standup-raven/server/plugin.exeargs[plugins/standup-raven/server/plugin.exe]"}
{"level":"debug","ts":1563781391.459904,"caller":"go-plugin/client.go:588","msg":"waiting for RPC address","plugin_id":"standup-raven","wrapped_extras":"pathplugins/standup-raven/server/plugin.exe"}
{"level":"debug","ts":1563781391.4891093,"caller":"go-plugin/client.go:774","msg":"plugin address","plugin_id":"standup-raven","wrapped_extras":"address/tmp/plugin767382531networkunixtimestamp2019-07-22T07:43:11.488Z"}
{"level":"info","ts":1563781391.49487,"caller":"go-plugin/stream.go:15","msg":"2019/07/22 07:43:11 RPC call to CreateBot API failed: rpc: can't find method Plugin.CreateBot","plugin_id":"standup-raven","source":"plugin_stderr"}
{"level":"debug","ts":1563781392.498302,"caller":"go-plugin/client.go:765","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4986403,"caller":"go-plugin/client.go:765","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc80419]","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.498658,"caller":"go-plugin/client.go:765","msg":"","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4986954,"caller":"go-plugin/client.go:765","msg":"goroutine 32 [running]:","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4990718,"caller":"go-plugin/client.go:765","msg":"github.com/standup-raven/standup-raven/server/vendor/github.com/mattermost/mattermost-server/plugin.(*HelpersImpl).EnsureBot(0xc0000335b0, 0xc0002522a0, 0x0, 0x0, 0x0, 0x0)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4991112,"caller":"go-plugin/client.go:765","msg":"\t/go/src/github.com/standup-raven/standup-raven/server/vendor/github.com/mattermost/mattermost-server/plugin/helpers_bots.go:61 +0xa29","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4991386,"caller":"go-plugin/client.go:765","msg":"main.(*Plugin).setUpBot(0xc00022b940, 0x0, 0x0, 0x0, 0x0)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.499154,"caller":"go-plugin/client.go:765","msg":"\t/go/src/github.com/standup-raven/standup-raven/server/plugin.go:62 +0x15f","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.499182,"caller":"go-plugin/client.go:765","msg":"main.(*Plugin).OnConfigurationChange(0xc00022b940, 0x0, 0x0)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4991977,"caller":"go-plugin/client.go:765","msg":"\t/go/src/github.com/standup-raven/standup-raven/server/plugin.go:103 +0xbd","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4992108,"caller":"go-plugin/client.go:765","msg":"main.(*Plugin).OnActivate(0xc00022b940, 0x0, 0x0)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4992268,"caller":"go-plugin/client.go:765","msg":"\t/go/src/github.com/standup-raven/standup-raven/server/plugin.go:36 +0x7a","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4992406,"caller":"go-plugin/client.go:765","msg":"github.com/standup-raven/standup-raven/server/vendor/github.com/mattermost/mattermost-server/plugin.(*hooksRPCServer).OnActivate(0xc000182600, 0xc00017a6d0, 0xc000176f70, 0x0, 0x0)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4992802,"caller":"go-plugin/client.go:765","msg":"\t/go/src/github.com/standup-raven/standup-raven/server/vendor/github.com/mattermost/mattermost-server/plugin/client_rpc.go:221 +0x5ef","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4992983,"caller":"go-plugin/client.go:765","msg":"reflect.Value.call(0xc00003b200, 0xc0003a8410, 0x13, 0xe61da7, 0x4, 0xc000111f18, 0x3, 0x3, 0x0, 0x0, ...)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4993126,"caller":"go-plugin/client.go:765","msg":"\t/usr/local/go/src/reflect/value.go:447 +0x1189","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4993246,"caller":"go-plugin/client.go:765","msg":"reflect.Value.Call(0xc00003b200, 0xc0003a8410, 0x13, 0xc000019718, 0x3, 0x3, 0x0, 0x0, 0x0)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.499335,"caller":"go-plugin/client.go:765","msg":"\t/usr/local/go/src/reflect/value.go:308 +0xca","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4993591,"caller":"go-plugin/client.go:765","msg":"net/rpc.(*service).call(0xc000084b00, 0xc0001b21e0, 0xc00017a520, 0xc00017a530, 0xc000254600, 0xc0001831a0, 0xd079c0, 0xc00017a6d0, 0x16, 0xd07a00, ...)","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.499374,"caller":"go-plugin/client.go:765","msg":"\t/usr/local/go/src/net/rpc/server.go:384 +0x251","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4993868,"caller":"go-plugin/client.go:765","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"standup-raven"}
{"level":"debug","ts":1563781392.4993994,"caller":"go-plugin/client.go:765","msg":"\t/usr/local/go/src/net/rpc/server.go:481 +0x607","plugin_id":"standup-raven"}
{"level":"error","ts":1563781392.5002668,"caller":"plugin/client_rpc.go:154","msg":"RPC call to OnActivate plugin failed.","plugin_id":"standup-raven","error":"unexpected EOF"}
{"level":"debug","ts":1563781392.50027,"caller":"go-plugin/client.go:538","msg":"plugin process exited","plugin_id":"standup-raven","wrapped_extras":"pathplugins/standup-raven/server/plugin.exe"}
{"level":"debug","ts":1563781392.5096798,"caller":"api4/plugin.go:20","msg":"EXPERIMENTAL: Initializing plugin api"}
{"level":"error","ts":1563781392.598874,"caller":"plugin/client_rpc_generated.go:66","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"standup-raven","error":"connection is shut down"}
{"level":"error","ts":1563781392.7085695,"caller":"plugin/client_rpc_generated.go:66","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"standup-raven","error":"connection is shut down"}
{"level":"error","ts":1563781405.8207664,"caller":"plugin/client_rpc.go:295","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"standup-raven","error":"connection is shut down"}
{"level":"error","ts":1563781410.8208716,"caller":"plugin/client_rpc.go:247","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","plugin_id":"standup-raven","serve_http_stream_id":2,"error":"timeout waiting for accept"}
{"level":"error","ts":1563781410.8208914,"caller":"plugin/client_rpc.go:268","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connecion","plugin_id":"standup-raven","error":"timeout waiting for accept"}
{"level":"debug","ts":1563781431.964634,"caller":"web/handlers.go:50","msg":"GET - /api/v4/plugins/webapp"}
{"level":"error","ts":1563781432.5455694,"caller":"plugin/client_rpc.go:295","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"standup-raven","error":"connection is shut down"}
{"level":"error","ts":1563781432.5609264,"caller":"plugin/client_rpc.go:295","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"standup-raven","error":"connection is shut down"}
{"level":"error","ts":1563781432.5760448,"caller":"plugin/client_rpc.go:295","msg":"Plugin failed to ServeHTTP, RPC call failed","plugin_id":"standup-raven","error":"connection is shut down"}
```

Do you have an Idea, what I can do, to fix it?

Mattermost is inside a Docker-Container
Mattermost Version 5.2.0

**Comment by harshilsharma63** [comment]
Hi @wgbeckmann The miminum supported Mattermost version is 5.12.
